server:
  port: 8080

spring:
  application:
    name: user
  datasource:
    username: postgres
    password: postgres123
    url: jdbc:postgresql://postgres-1.cehuxmoshf3z.us-west-2.rds.amazonaws.com:5432/your-database-name
    hikari:
      max-lifetime: 600000
    dbcp2:
      test-while-idle: true
      test-on-borrow: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true